import Footer from "./footer/Footer";
import Header from "./header/Header";
import { Metadata } from "next";
export const metadata : Metadata= {
  title:{
    template:"",
    default: "pokemon",
    absolute:"",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
